/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Maverick.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Maverick(props) {
  const { nodes, materials } = useGLTF('models/Maverick.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wipers.geometry} material={materials['black matt']} />
      <mesh geometry={nodes.text_logo.geometry} material={materials['chrome.001']} />
      <mesh geometry={nodes.trailer_panel.geometry} material={materials['black matt']} />
      <mesh geometry={nodes.exhaust_pipe.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.antenna.geometry} material={materials['grey matt.002']} />
      <mesh geometry={nodes.bottom.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.body.geometry}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.chasis.geometry} material={materials['grey matt.002']} />
      <mesh geometry={nodes.rear_bumper.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Dash.geometry} material={materials.dash} />
      <mesh geometry={nodes.Trunk.geometry} material={materials.dash} />
      <mesh geometry={nodes.Mesh.geometry} material={materials.Ford_logo} />
      <mesh geometry={nodes.Mesh_1.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Mesh001.geometry} material={materials['light grey']} />
      <mesh geometry={nodes.Mesh001_1.geometry} material={materials['grey matt']} />
      <mesh geometry={nodes.Mesh004.geometry} material={materials['light grey.001']} />
      <mesh geometry={nodes.Mesh004_1.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.Mesh004_2.geometry} material={materials['chrome gloss']} />
      <mesh geometry={nodes.Mesh004_3.geometry} material={materials.light} />
      <mesh geometry={nodes.Mesh005.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh005_1.geometry} material={materials['light grey.001']} />
      <mesh geometry={nodes.Mesh006.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.Mesh006_1.geometry} material={materials['Glass_red.001']} />
      <mesh geometry={nodes.Mesh006_2.geometry} material={materials['black matt']} />
      <mesh geometry={nodes.Mesh006_3.geometry} material={materials['light grey.001']} />
      <mesh geometry={nodes.Mesh006_4.geometry} material={materials.Glass_red} />
      <mesh geometry={nodes.Mesh006_5.geometry} material={materials['chrome gloss']} />
      <mesh geometry={nodes.Mesh008.geometry} material={materials['grey matt.001']} />
      <mesh geometry={nodes.Mesh008_1.geometry} material={materials.plate} />
      <mesh geometry={nodes.Mesh010.geometry} material={materials['grey matt.002']} />
      <mesh geometry={nodes.Mesh010_1.geometry} material={materials.mirror} />
      <mesh geometry={nodes.Mesh013.geometry} material={materials.glass} />
      <mesh geometry={nodes.Mesh013_1.geometry} material={materials['grey matt.002']} />
      <mesh geometry={nodes.Mesh013_2.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh013_3.geometry} material={materials['light grey.001']} />
      <mesh geometry={nodes.Mesh013_4.geometry} material={materials.Glass_orange} />
      <mesh geometry={nodes.Mesh013_5.geometry} material={materials['chrome gloss']} />
      <mesh geometry={nodes.Mesh014.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh014_1.geometry} material={materials.vray_Base} />
      <mesh geometry={nodes.Mesh014_2.geometry} material={materials.mirror} />
      <mesh geometry={nodes.Mesh015.geometry} material={materials.glass} />
      <mesh geometry={nodes.Mesh015_1.geometry} material={materials['glass black']} />
      <mesh geometry={nodes.Mesh016.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh016_1.geometry} material={materials['chrome gloss.001']} />
      <mesh geometry={nodes.Mesh016_2.geometry} material={materials.Ford_logo} />
      <mesh geometry={nodes.Mesh017.geometry} material={materials.tire} />
      <mesh geometry={nodes.Mesh017_1.geometry} material={materials['tire-side']} />
      <mesh geometry={nodes.Mesh018.geometry} material={materials.tire} />
      <mesh geometry={nodes.Mesh018_1.geometry} material={materials['tire-side']} />
      <mesh geometry={nodes.Mesh020.geometry} material={materials.tire} />
      <mesh geometry={nodes.Mesh020_1.geometry} material={materials['tire-side']} />
      <mesh geometry={nodes.Mesh022.geometry} material={materials['grey matt.002']} />
      <mesh geometry={nodes.Mesh022_1.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh022_2.geometry} material={materials.vray_Base} />
      <mesh geometry={nodes.Mesh022_3.geometry} material={materials['light grey.001']} />
      <mesh geometry={nodes.Mesh022_4.geometry} material={materials.Glass_orange} />
      <mesh geometry={nodes.Mesh025.geometry} material={materials.tire} />
      <mesh geometry={nodes.Mesh025_1.geometry} material={materials['tire-side']} />
      <mesh geometry={nodes.Mesh027.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh027_1.geometry} material={materials['chrome gloss.001']} />
      <mesh geometry={nodes.Mesh027_2.geometry} material={materials.Ford_logo} />
      <mesh geometry={nodes.Mesh028.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh028_1.geometry} material={materials['chrome gloss.001']} />
      <mesh geometry={nodes.Mesh028_2.geometry} material={materials.Ford_logo} />
      <mesh geometry={nodes.Mesh029.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh029_1.geometry} material={materials['chrome gloss.001']} />
      <mesh geometry={nodes.Mesh029_2.geometry} material={materials.Ford_logo} />
    </group>
  )
}

useGLTF.preload('/Maverick.glb')
