/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Maverick.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from "valtio"
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';

export function Maverick(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/Maverick.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wipers.geometry} material={materials['black matt']} />
      <mesh geometry={nodes.text_logo.geometry} material={materials['chrome.001']} />
      <mesh geometry={nodes.trailer_panel.geometry} material={materials['black matt']} />
      <mesh geometry={nodes.exhaust_pipe.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.antenna.geometry} material={materials['grey matt.002']} />
      <mesh geometry={nodes.bottom.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.body.geometry} material={materials.BaseMtl} material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
      <mesh geometry={nodes.chasis.geometry} material={materials['grey matt.002']} />
      <mesh geometry={nodes.rear_bumper.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.body001.geometry} material={materials['Slaughter.001']} material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
      <mesh geometry={nodes.body002.geometry} material={materials.BatLady} material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
      <mesh geometry={nodes.body003.geometry} material={materials.BrakeLine} material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
      <mesh geometry={nodes.body004.geometry} material={materials.Danger} material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
      <mesh geometry={nodes.Dash.geometry} material={materials.dash} />
      <mesh geometry={nodes.Trunk.geometry} material={materials.dash} />
      <mesh geometry={nodes.body005.geometry} material={materials.Embers} material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
      <mesh geometry={nodes.body006.geometry} material={materials['SpiderID.001']} material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
      <mesh geometry={nodes.body007.geometry} material={materials.Fluid} material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
      <mesh geometry={nodes.body008.geometry} material={materials.HotRods} material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
      <mesh geometry={nodes.body009.geometry} material={materials['Mayan.001']} material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
      <mesh geometry={nodes.body010.geometry} material={materials['SeaBreeze.001']} material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
      <mesh geometry={nodes.body011.geometry} material={materials['ShapeShifter.001']} material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
      <mesh geometry={nodes.body012.geometry} material={materials['Silk.001']} material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
      <mesh geometry={nodes.body013.geometry} material={materials['SnakeSkin.001']} material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
      <mesh geometry={nodes.body014.geometry} material={materials.Flare} material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
      <mesh geometry={nodes.body015.geometry} material={materials.Dominator} material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
      <mesh geometry={nodes.body016.geometry} material={materials['TopGun.001']} material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
      <mesh geometry={nodes.body017.geometry} material={materials.Explosion} material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
      <mesh geometry={nodes.body018.geometry} material={materials['WildWest.001']} material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
      <mesh geometry={nodes.body019.geometry} material={materials['Zombie.001']} material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
      <mesh geometry={nodes.Mesh.geometry} material={materials.Ford_logo} />
      <mesh geometry={nodes.Mesh_1.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Mesh001.geometry} material={materials['light grey']} />
      <mesh geometry={nodes.Mesh001_1.geometry} material={materials['grey matt']} />
      <mesh geometry={nodes.Mesh004.geometry} material={materials['light grey.001']} />
      <mesh geometry={nodes.Mesh004_1.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.Mesh004_2.geometry} material={materials['chrome gloss']} />
      <mesh geometry={nodes.Mesh004_3.geometry} material={materials.light} />
      <mesh geometry={nodes.Mesh005.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh005_1.geometry} material={materials['light grey.001']} />
      <mesh geometry={nodes.Mesh006.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.Mesh006_1.geometry} material={materials['Glass_red.001']} />
      <mesh geometry={nodes.Mesh006_2.geometry} material={materials['black matt']} />
      <mesh geometry={nodes.Mesh006_3.geometry} material={materials['light grey.001']} />
      <mesh geometry={nodes.Mesh006_4.geometry} material={materials.Glass_red} />
      <mesh geometry={nodes.Mesh006_5.geometry} material={materials['chrome gloss']} />
      <mesh geometry={nodes.Mesh008.geometry} material={materials['grey matt.001']} />
      <mesh geometry={nodes.Mesh008_1.geometry} material={materials.plate} />
      <mesh geometry={nodes.Mesh010.geometry} material={materials['grey matt.002']} />
      <mesh geometry={nodes.Mesh010_1.geometry} material={materials.mirror} />
      <mesh geometry={nodes.Mesh013.geometry} material={materials.glass} />
      <mesh geometry={nodes.Mesh013_1.geometry} material={materials['grey matt.002']} />
      <mesh geometry={nodes.Mesh013_2.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh013_3.geometry} material={materials['light grey.001']} />
      <mesh geometry={nodes.Mesh013_4.geometry} material={materials.Glass_orange} />
      <mesh geometry={nodes.Mesh013_5.geometry} material={materials['chrome gloss']} />
      <mesh geometry={nodes.Mesh014.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh014_1.geometry} material={materials.vray_Base} />
      <mesh geometry={nodes.Mesh014_2.geometry} material={materials.mirror} />
      <mesh geometry={nodes.Mesh015.geometry} material={materials.glass} />
      <mesh geometry={nodes.Mesh015_1.geometry} material={materials['glass black']} />
      <mesh geometry={nodes.Mesh016.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh016_1.geometry} material={materials['chrome gloss.001']} />
      <mesh geometry={nodes.Mesh016_2.geometry} material={materials.Ford_logo} />
      <mesh geometry={nodes.Mesh017.geometry} material={materials.tire} />
      <mesh geometry={nodes.Mesh017_1.geometry} material={materials['tire-side']} />
      <mesh geometry={nodes.Mesh018.geometry} material={materials.tire} />
      <mesh geometry={nodes.Mesh018_1.geometry} material={materials['tire-side']} />
      <mesh geometry={nodes.Mesh020.geometry} material={materials.tire} />
      <mesh geometry={nodes.Mesh020_1.geometry} material={materials['tire-side']} />
      <mesh geometry={nodes.Mesh022.geometry} material={materials['grey matt.002']} />
      <mesh geometry={nodes.Mesh022_1.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh022_2.geometry} material={materials.vray_Base} />
      <mesh geometry={nodes.Mesh022_3.geometry} material={materials['light grey.001']} />
      <mesh geometry={nodes.Mesh022_4.geometry} material={materials.Glass_orange} />
      <mesh geometry={nodes.Mesh025.geometry} material={materials.tire} />
      <mesh geometry={nodes.Mesh025_1.geometry} material={materials['tire-side']} />
      <mesh geometry={nodes.Mesh027.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh027_1.geometry} material={materials['chrome gloss.001']} />
      <mesh geometry={nodes.Mesh027_2.geometry} material={materials.Ford_logo} />
      <mesh geometry={nodes.Mesh028.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh028_1.geometry} material={materials['chrome gloss.001']} />
      <mesh geometry={nodes.Mesh028_2.geometry} material={materials.Ford_logo} />
      <mesh geometry={nodes.Mesh029.geometry} material={materials['dark grey']} />
      <mesh geometry={nodes.Mesh029_1.geometry} material={materials['chrome gloss.001']} />
      <mesh geometry={nodes.Mesh029_2.geometry} material={materials.Ford_logo} />
    </group>
  )
}

useGLTF.preload('/models/Maverick.glb')
